//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinJuke {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PinJuke.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Accept license ähnelt.
        /// </summary>
        public static string AcceptLicense {
            get {
                return ResourceManager.GetString("AcceptLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add new playlist… ähnelt.
        /// </summary>
        public static string AddNewPlaylist {
            get {
                return ResourceManager.GetString("AddNewPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back ähnelt.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Background image file ähnelt.
        /// </summary>
        public static string BackgroundImageFile {
            get {
                return ResourceManager.GetString("BackgroundImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show idle videl ähnelt.
        /// </summary>
        public static string BackgroundTypeShowIdleVideo {
            get {
                return ResourceManager.GetString("BackgroundTypeShowIdleVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show loop video ähnelt.
        /// </summary>
        public static string BackgroundTypeShowLoopVideo {
            get {
                return ResourceManager.GetString("BackgroundTypeShowLoopVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show milkdrop visualizations ähnelt.
        /// </summary>
        public static string BackgroundTypeShowMilkdropVisualizations {
            get {
                return ResourceManager.GetString("BackgroundTypeShowMilkdropVisualizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show specified image ähnelt.
        /// </summary>
        public static string BackgroundTypeShowSpecifiedImage {
            get {
                return ResourceManager.GetString("BackgroundTypeShowSpecifiedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die App file version ähnelt.
        /// </summary>
        public static string BeaconAppFileVersion {
            get {
                return ResourceManager.GetString("BeaconAppFileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die App name ähnelt.
        /// </summary>
        public static string BeaconAppName {
            get {
                return ResourceManager.GetString("BeaconAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die App version ähnelt.
        /// </summary>
        public static string BeaconAppVersion {
            get {
                return ResourceManager.GetString("BeaconAppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Controller names ähnelt.
        /// </summary>
        public static string BeaconControllerNames {
            get {
                return ResourceManager.GetString("BeaconControllerNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DOF enabled ähnelt.
        /// </summary>
        public static string BeaconDofEnabled {
            get {
                return ResourceManager.GetString("BeaconDofEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error querying the data ({0}) ähnelt.
        /// </summary>
        public static string BeaconErrorQuerying {
            get {
                return ResourceManager.GetString("BeaconErrorQuerying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installed RAM ähnelt.
        /// </summary>
        public static string BeaconInstalledRam {
            get {
                return ResourceManager.GetString("BeaconInstalledRam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Locale ähnelt.
        /// </summary>
        public static string BeaconLocale {
            get {
                return ResourceManager.GetString("BeaconLocale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Querying data… ähnelt.
        /// </summary>
        public static string BeaconQueryingData {
            get {
                return ResourceManager.GetString("BeaconQueryingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Timezone ähnelt.
        /// </summary>
        public static string BeaconTimezone {
            get {
                return ResourceManager.GetString("BeaconTimezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The software determines the following data about your system: ähnelt.
        /// </summary>
        public static string BeaconWhatIsIncluded {
            get {
                return ResourceManager.GetString("BeaconWhatIsIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Browser is visible ähnelt.
        /// </summary>
        public static string BrowserFunction {
            get {
                return ResourceManager.GetString("BrowserFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (Up) ähnelt.
        /// </summary>
        public static string BrowserUp {
            get {
                return ResourceManager.GetString("BrowserUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Button ähnelt.
        /// </summary>
        public static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit button ähnelt.
        /// </summary>
        public static string ButtonExit {
            get {
                return ResourceManager.GetString("ButtonExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit app ähnelt.
        /// </summary>
        public static string ButtonExitBrowserFunction {
            get {
                return ResourceManager.GetString("ButtonExitBrowserFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit app ähnelt.
        /// </summary>
        public static string ButtonExitRegularFunction {
            get {
                return ResourceManager.GetString("ButtonExitRegularFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Flipper button
        ///left/right ähnelt.
        /// </summary>
        public static string ButtonFlipperLeftRight {
            get {
                return ResourceManager.GetString("ButtonFlipperLeftRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Navigate back/forward ähnelt.
        /// </summary>
        public static string ButtonFlipperLeftRightBrowserFunction {
            get {
                return ResourceManager.GetString("ButtonFlipperLeftRightBrowserFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Track back/forward ähnelt.
        /// </summary>
        public static string ButtonFlipperLeftRightRegularFunction {
            get {
                return ResourceManager.GetString("ButtonFlipperLeftRightRegularFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Launch ball button ähnelt.
        /// </summary>
        public static string ButtonLaunchBall {
            get {
                return ResourceManager.GetString("ButtonLaunchBall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Folder: follow
        ///Track: restart ähnelt.
        /// </summary>
        public static string ButtonLaunchBallBrowserFunction {
            get {
                return ResourceManager.GetString("ButtonLaunchBallBrowserFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open track browser ähnelt.
        /// </summary>
        public static string ButtonLaunchBallRegularFunction {
            get {
                return ResourceManager.GetString("ButtonLaunchBallRegularFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Magna save button
        ///left/right ähnelt.
        /// </summary>
        public static string ButtonMagnaSaveLeftRight {
            get {
                return ResourceManager.GetString("ButtonMagnaSaveLeftRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Visualization back/forward ähnelt.
        /// </summary>
        public static string ButtonMagnaSaveLeftRightBrowserFunction {
            get {
                return ResourceManager.GetString("ButtonMagnaSaveLeftRightBrowserFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Volume ähnelt.
        /// </summary>
        public static string ButtonMagnaSaveLeftRightRegularFunction {
            get {
                return ResourceManager.GetString("ButtonMagnaSaveLeftRightRegularFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start button ähnelt.
        /// </summary>
        public static string ButtonStart {
            get {
                return ResourceManager.GetString("ButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Play/pause ähnelt.
        /// </summary>
        public static string ButtonStartBrowserFunction {
            get {
                return ResourceManager.GetString("ButtonStartBrowserFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Play/pause ähnelt.
        /// </summary>
        public static string ButtonStartRegularFunction {
            get {
                return ResourceManager.GetString("ButtonStartRegularFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check for application updates (when the Configurator is run) ähnelt.
        /// </summary>
        public static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose directory… ähnelt.
        /// </summary>
        public static string ChooseDirectory {
            get {
                return ResourceManager.GetString("ChooseDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose file… ähnelt.
        /// </summary>
        public static string ChooseFile {
            get {
                return ResourceManager.GetString("ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configuration of the displays ähnelt.
        /// </summary>
        public static string ConfigurationOfDisplays {
            get {
                return ResourceManager.GetString("ConfigurationOfDisplays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configuration of DOF ähnelt.
        /// </summary>
        public static string ConfigurationOfDof {
            get {
                return ResourceManager.GetString("ConfigurationOfDof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Consent to the data collection ähnelt.
        /// </summary>
        public static string ConsentToDataCollection {
            get {
                return ResourceManager.GetString("ConsentToDataCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Album ähnelt.
        /// </summary>
        public static string CoverAlbum {
            get {
                return ResourceManager.GetString("CoverAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Artist ähnelt.
        /// </summary>
        public static string CoverArtist {
            get {
                return ResourceManager.GetString("CoverArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Title ähnelt.
        /// </summary>
        public static string CoverTitle {
            get {
                return ResourceManager.GetString("CoverTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Year ähnelt.
        /// </summary>
        public static string CoverYear {
            get {
                return ResourceManager.GetString("CoverYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create ähnelt.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create a playlist after completion ähnelt.
        /// </summary>
        public static string CreatePlaylistAfterCompletion {
            get {
                return ResourceManager.GetString("CreatePlaylistAfterCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hardware &amp; Software Survey ähnelt.
        /// </summary>
        public static string DataOnSoftwareUsage {
            get {
                return ResourceManager.GetString("DataOnSoftwareUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die We kindly ask for your consent to collect pseudonymized data regarding the use of our software and hardware. This information will help us understand how the software is perceived and utilized by users. Aggregated insights may be shared with the community (e.g., in the form of reports or analyses). ähnelt.
        /// </summary>
        public static string DataOnSoftwareUsageDescription {
            get {
                return ResourceManager.GetString("DataOnSoftwareUsageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The data is stored in a Firebase database (a Google product). Deletion of the data cannot be requested. ähnelt.
        /// </summary>
        public static string DataOnSoftwareUsageStorage {
            get {
                return ResourceManager.GetString("DataOnSoftwareUsageStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disabled ähnelt.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backglass ähnelt.
        /// </summary>
        public static string DisplayBackGlass {
            get {
                return ResourceManager.GetString("DisplayBackGlass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DMD ähnelt.
        /// </summary>
        public static string DisplayDmd {
            get {
                return ResourceManager.GetString("DisplayDmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Playfield ähnelt.
        /// </summary>
        public static string DisplayPlayField {
            get {
                return ResourceManager.GetString("DisplayPlayField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Topper ähnelt.
        /// </summary>
        public static string DisplayTopper {
            get {
                return ResourceManager.GetString("DisplayTopper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DOF ähnelt.
        /// </summary>
        public static string Dof {
            get {
                return ResourceManager.GetString("Dof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Direct Output Framework can be used to control the controllers connected to your hardware. ähnelt.
        /// </summary>
        public static string DofDescription {
            get {
                return ResourceManager.GetString("DofDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GlobalConfig_B2SServer.xml ähnelt.
        /// </summary>
        public static string DofGlobalConfigFilePath {
            get {
                return ResourceManager.GetString("DofGlobalConfigFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable ähnelt.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enabled ähnelt.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable DOF ähnelt.
        /// </summary>
        public static string EnableDof {
            get {
                return ResourceManager.GetString("EnableDof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show playback status ähnelt.
        /// </summary>
        public static string EnablePlaybackStatus {
            get {
                return ResourceManager.GetString("EnablePlaybackStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Play themed video skins ähnelt.
        /// </summary>
        public static string EnableThemeVideo {
            get {
                return ResourceManager.GetString("EnableThemeVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show track browser ähnelt.
        /// </summary>
        public static string EnableTrackBrowser {
            get {
                return ResourceManager.GetString("EnableTrackBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show track cover and information ähnelt.
        /// </summary>
        public static string EnableTrackCover {
            get {
                return ResourceManager.GetString("EnableTrackCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error initializing DOF: &quot;{0}&quot; ähnelt.
        /// </summary>
        public static string ErrorDofInit {
            get {
                return ResourceManager.GetString("ErrorDofInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error setting up DOF: &quot;{0}&quot; ähnelt.
        /// </summary>
        public static string ErrorDofSetup {
            get {
                return ResourceManager.GetString("ErrorDofSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error reading file &quot;{0}&quot;. ähnelt.
        /// </summary>
        public static string ErrorReadingFile {
            get {
                return ResourceManager.GetString("ErrorReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error writing file &quot;{0}&quot;. ähnelt.
        /// </summary>
        public static string ErrorWritingFile {
            get {
                return ResourceManager.GetString("ErrorWritingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New versions of PinJuke can be found at: ähnelt.
        /// </summary>
        public static string FindTheDownloadPageAt {
            get {
                return ResourceManager.GetString("FindTheDownloadPageAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The project page (including source code) can be found at: ähnelt.
        /// </summary>
        public static string FindTheProjectPageAt {
            get {
                return ResourceManager.GetString("FindTheProjectPageAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Finish ähnelt.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get display position from PinUP ähnelt.
        /// </summary>
        public static string GetDisplayPositionFromPinup {
            get {
                return ResourceManager.GetString("GetDisplayPositionFromPinup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get display positions from PinUP ähnelt.
        /// </summary>
        public static string GetDisplayPositionsFromPinup {
            get {
                return ResourceManager.GetString("GetDisplayPositionsFromPinup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Global configuration ähnelt.
        /// </summary>
        public static string GlobalConfiguration {
            get {
                return ResourceManager.GetString("GlobalConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Idle background type ähnelt.
        /// </summary>
        public static string IdleBackgroundType {
            get {
                return ResourceManager.GetString("IdleBackgroundType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die INI file ähnelt.
        /// </summary>
        public static string IniFile {
            get {
                return ResourceManager.GetString("IniFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die JPEG file ähnelt.
        /// </summary>
        public static string JpegFile {
            get {
                return ResourceManager.GetString("JpegFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keyboard ähnelt.
        /// </summary>
        public static string Keyboard {
            get {
                return ResourceManager.GetString("Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Browse ähnelt.
        /// </summary>
        public static string KeyBrowse {
            get {
                return ResourceManager.GetString("KeyBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
        /// </summary>
        public static string KeyExit {
            get {
                return ResourceManager.GetString("KeyExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next/forward ähnelt.
        /// </summary>
        public static string KeyNext {
            get {
                return ResourceManager.GetString("KeyNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Play/pause ähnelt.
        /// </summary>
        public static string KeyPlayPause {
            get {
                return ResourceManager.GetString("KeyPlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back/previous ähnelt.
        /// </summary>
        public static string KeyPrevious {
            get {
                return ResourceManager.GetString("KeyPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Volume down ähnelt.
        /// </summary>
        public static string KeyVolumeDown {
            get {
                return ResourceManager.GetString("KeyVolumeDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Volume up ähnelt.
        /// </summary>
        public static string KeyVolumeUp {
            get {
                return ResourceManager.GetString("KeyVolumeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die License ähnelt.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Media path ähnelt.
        /// </summary>
        public static string MediaPath {
            get {
                return ResourceManager.GetString("MediaPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Milkdrop ähnelt.
        /// </summary>
        public static string Milkdrop {
            get {
                return ResourceManager.GetString("Milkdrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Presets path ähnelt.
        /// </summary>
        public static string MilkdropPresetsPath {
            get {
                return ResourceManager.GetString("MilkdropPresetsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Textures path ähnelt.
        /// </summary>
        public static string MilkdropTexturesPath {
            get {
                return ResourceManager.GetString("MilkdropTexturesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MP4 file ähnelt.
        /// </summary>
        public static string Mp4File {
            get {
                return ResourceManager.GetString("Mp4File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Path to music directory ähnelt.
        /// </summary>
        public static string MusicPath {
            get {
                return ResourceManager.GetString("MusicPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New playlist configuration ähnelt.
        /// </summary>
        public static string NewPlaylistConfiguration {
            get {
                return ResourceManager.GetString("NewPlaylistConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next ähnelt.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No audio device found. ähnelt.
        /// </summary>
        public static string NoAudioDeviceFound {
            get {
                return ResourceManager.GetString("NoAudioDeviceFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If you do not have a separate monitor for the DMD output, you can have the DMD window overlay the backglass window, for example. ähnelt.
        /// </summary>
        public static string NoSeparateDmdMonitorHint {
            get {
                return ResourceManager.GetString("NoSeparateDmdMonitorHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overview of the hardware controls ähnelt.
        /// </summary>
        public static string OverviewOfTheButtons {
            get {
                return ResourceManager.GetString("OverviewOfTheButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;{0}&quot; not found. ähnelt.
        /// </summary>
        public static string PathNotFound {
            get {
                return ResourceManager.GetString("PathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Playback background type ähnelt.
        /// </summary>
        public static string PlaybackBackgroundType {
            get {
                return ResourceManager.GetString("PlaybackBackgroundType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Player ähnelt.
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Playlist configuration ähnelt.
        /// </summary>
        public static string PlaylistConfiguration {
            get {
                return ResourceManager.GetString("PlaylistConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Playback at program start ähnelt.
        /// </summary>
        public static string PlayOnStartup {
            get {
                return ResourceManager.GetString("PlayOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PinJuke is provided under the displayed license. ähnelt.
        /// </summary>
        public static string ProvidedUnderDisplayedLicense {
            get {
                return ResourceManager.GetString("ProvidedUnderDisplayedLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Height ähnelt.
        /// </summary>
        public static string RectHeight {
            get {
                return ResourceManager.GetString("RectHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Left ähnelt.
        /// </summary>
        public static string RectLeft {
            get {
                return ResourceManager.GetString("RectLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Top ähnelt.
        /// </summary>
        public static string RectTop {
            get {
                return ResourceManager.GetString("RectTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Width ähnelt.
        /// </summary>
        public static string RectWidth {
            get {
                return ResourceManager.GetString("RectWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refuse the collection of data ähnelt.
        /// </summary>
        public static string RefuseDataCollection {
            get {
                return ResourceManager.GetString("RefuseDataCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Regular function ähnelt.
        /// </summary>
        public static string RegularFunction {
            get {
                return ResourceManager.GetString("RegularFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Relative path ähnelt.
        /// </summary>
        public static string RelativePath {
            get {
                return ResourceManager.GetString("RelativePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Re-run setup ähnelt.
        /// </summary>
        public static string RerunSetup {
            get {
                return ResourceManager.GetString("RerunSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rotation ähnelt.
        /// </summary>
        public static string Rotation {
            get {
                return ResourceManager.GetString("Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start with current playlist ähnelt.
        /// </summary>
        public static string RunCurrentPlaylist {
            get {
                return ResourceManager.GetString("RunCurrentPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save all ähnelt.
        /// </summary>
        public static string SaveAll {
            get {
                return ResourceManager.GetString("SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scale ähnelt.
        /// </summary>
        public static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die See what data is collected. ähnelt.
        /// </summary>
        public static string SeeWhatDataIsCollected {
            get {
                return ResourceManager.GetString("SeeWhatDataIsCollected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the GlobalConfig_B2SServer.xml file: ähnelt.
        /// </summary>
        public static string SelectDofConfigFile {
            get {
                return ResourceManager.GetString("SelectDofConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Behavior on program start ähnelt.
        /// </summary>
        public static string StartupTrackType {
            get {
                return ResourceManager.GetString("StartupTrackType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First track from directory ähnelt.
        /// </summary>
        public static string StartupTrackTypeFirstTrack {
            get {
                return ResourceManager.GetString("StartupTrackTypeFirstTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Continue with the last track played ähnelt.
        /// </summary>
        public static string StartupTrackTypeLastPlayedTrack {
            get {
                return ResourceManager.GetString("StartupTrackTypeLastPlayedTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Random playback sequence ähnelt.
        /// </summary>
        public static string StartupTrackTypeRandomMode {
            get {
                return ResourceManager.GetString("StartupTrackTypeRandomMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next ähnelt.
        /// </summary>
        public static string StateNext {
            get {
                return ResourceManager.GetString("StateNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pause ähnelt.
        /// </summary>
        public static string StatePause {
            get {
                return ResourceManager.GetString("StatePause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Play ähnelt.
        /// </summary>
        public static string StatePlay {
            get {
                return ResourceManager.GetString("StatePlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Previous ähnelt.
        /// </summary>
        public static string StatePrevious {
            get {
                return ResourceManager.GetString("StatePrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop ähnelt.
        /// </summary>
        public static string StateStop {
            get {
                return ResourceManager.GetString("StateStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tilt! ähnelt.
        /// </summary>
        public static string StateTilt {
            get {
                return ResourceManager.GetString("StateTilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Volume {0:00}% ähnelt.
        /// </summary>
        public static string StateVolumeXPercent {
            get {
                return ResourceManager.GetString("StateVolumeXPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Global Configuration ähnelt.
        /// </summary>
        public static string TabGlobalConfiguration {
            get {
                return ResourceManager.GetString("TabGlobalConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Playlist: ähnelt.
        /// </summary>
        public static string TabPlaylistConfiguration {
            get {
                return ResourceManager.GetString("TabPlaylistConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Theme video idle file ähnelt.
        /// </summary>
        public static string ThemeVideoIdleFile {
            get {
                return ResourceManager.GetString("ThemeVideoIdleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Theme video loop file ähnelt.
        /// </summary>
        public static string ThemeVideoLoopFile {
            get {
                return ResourceManager.GetString("ThemeVideoLoopFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Theme video rotation ähnelt.
        /// </summary>
        public static string ThemeVideoRotation {
            get {
                return ResourceManager.GetString("ThemeVideoRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Theme video start file ähnelt.
        /// </summary>
        public static string ThemeVideoStartFile {
            get {
                return ResourceManager.GetString("ThemeVideoStartFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Theme video stop file ähnelt.
        /// </summary>
        public static string ThemeVideoStopFile {
            get {
                return ResourceManager.GetString("ThemeVideoStopFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Further information can be found in the documentation ähnelt.
        /// </summary>
        public static string ToolTipDocumentation {
            get {
                return ResourceManager.GetString("ToolTipDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show track browser on ähnelt.
        /// </summary>
        public static string TrackBrowserOn {
            get {
                return ResourceManager.GetString("TrackBrowserOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Checking for updates… ähnelt.
        /// </summary>
        public static string UpdateChecking {
            get {
                return ResourceManager.GetString("UpdateChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A new version is available: ähnelt.
        /// </summary>
        public static string UpdateNewVersionAvailable {
            get {
                return ResourceManager.GetString("UpdateNewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to start the configurator? ähnelt.
        /// </summary>
        public static string WantToStartConfigurator {
            get {
                return ResourceManager.GetString("WantToStartConfigurator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welcome to PinJuke! ähnelt.
        /// </summary>
        public static string WelcomeToPinJuke {
            get {
                return ResourceManager.GetString("WelcomeToPinJuke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die We will set up PinJuke on the following pages. ähnelt.
        /// </summary>
        public static string WillSetUpPinJuke {
            get {
                return ResourceManager.GetString("WillSetUpPinJuke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (Will try to recognize your controllers with the help of DOF.) ähnelt.
        /// </summary>
        public static string WillTryToRecognizeControllers {
            get {
                return ResourceManager.GetString("WillTryToRecognizeControllers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die XML file ähnelt.
        /// </summary>
        public static string XmlFile {
            get {
                return ResourceManager.GetString("XmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are all set! ähnelt.
        /// </summary>
        public static string YouAreAllSet {
            get {
                return ResourceManager.GetString("YouAreAllSet", resourceCulture);
            }
        }
    }
}
