//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinJuke {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PinJuke.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Up).
        /// </summary>
        internal static string BrowserUp {
            get {
                return ResourceManager.GetString("BrowserUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose directory….
        /// </summary>
        internal static string ChooseDirectory {
            get {
                return ResourceManager.GetString("ChooseDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose file….
        /// </summary>
        internal static string ChooseFile {
            get {
                return ResourceManager.GetString("ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        internal static string CoverAlbum {
            get {
                return ResourceManager.GetString("CoverAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        internal static string CoverArtist {
            get {
                return ResourceManager.GetString("CoverArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string CoverTitle {
            get {
                return ResourceManager.GetString("CoverTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string CoverYear {
            get {
                return ResourceManager.GetString("CoverYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading file &quot;{0}&quot;..
        /// </summary>
        internal static string ErrorReadingFile {
            get {
                return ResourceManager.GetString("ErrorReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error writing file &quot;{0}&quot;..
        /// </summary>
        internal static string ErrorWritingFile {
            get {
                return ResourceManager.GetString("ErrorWritingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INI file.
        /// </summary>
        internal static string IniFile {
            get {
                return ResourceManager.GetString("IniFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG file.
        /// </summary>
        internal static string JpegFile {
            get {
                return ResourceManager.GetString("JpegFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new playlist….
        /// </summary>
        internal static string LabelAddNewPlaylist {
            get {
                return ResourceManager.GetString("LabelAddNewPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Further information can be found in the documentation:.
        /// </summary>
        internal static string LabelDocumentation {
            get {
                return ResourceManager.GetString("LabelDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with current playlist.
        /// </summary>
        internal static string LabelRunCurrentPlaylist {
            get {
                return ResourceManager.GetString("LabelRunCurrentPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all.
        /// </summary>
        internal static string LabelSaveAll {
            get {
                return ResourceManager.GetString("LabelSaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP4 file.
        /// </summary>
        internal static string Mp4File {
            get {
                return ResourceManager.GetString("Mp4File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No audio device found..
        /// </summary>
        internal static string NoAudioDeviceFound {
            get {
                return ResourceManager.GetString("NoAudioDeviceFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; not found..
        /// </summary>
        internal static string PathNotFound {
            get {
                return ResourceManager.GetString("PathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative path.
        /// </summary>
        internal static string RelativePath {
            get {
                return ResourceManager.GetString("RelativePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string StateNext {
            get {
                return ResourceManager.GetString("StateNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string StatePause {
            get {
                return ResourceManager.GetString("StatePause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string StatePlay {
            get {
                return ResourceManager.GetString("StatePlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string StatePrevious {
            get {
                return ResourceManager.GetString("StatePrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string StateStop {
            get {
                return ResourceManager.GetString("StateStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilt!.
        /// </summary>
        internal static string StateTilt {
            get {
                return ResourceManager.GetString("StateTilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume {0:00}%.
        /// </summary>
        internal static string StateVolumeXPercent {
            get {
                return ResourceManager.GetString("StateVolumeXPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to start the configurator?.
        /// </summary>
        internal static string WantToStartConfigurator {
            get {
                return ResourceManager.GetString("WantToStartConfigurator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML file.
        /// </summary>
        internal static string XmlFile {
            get {
                return ResourceManager.GetString("XmlFile", resourceCulture);
            }
        }
    }
}
