name: Build release for tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build release and upload
    runs-on: windows-2022 # For a list of available runner types, refer to
                          # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # https://github.com/actions/runner-images?tab=readme-ov-file#available-images
      - name: Get FFmpeg
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "GyanD/codexffmpeg"
          tag: '7.0.2'
          fileName: "ffmpeg-7.0.2-full_build-shared.zip"
          extract: true
      - name: Copy FFmpeg
        # Must be a Powershell script.
        run: |
          cp ffmpeg-7.0.2-full_build-shared/LICENSE src/PinJuke/ffmpeg/
          cp ffmpeg-7.0.2-full_build-shared/README.txt src/PinJuke/ffmpeg/
          cp ffmpeg-7.0.2-full_build-shared/bin/*.dll src/PinJuke/ffmpeg/
      - name: Build projectm
        run: |
          cd deps\projectm
          cmake . -B build -DCMAKE_BUILD_TYPE=Release "-DCMAKE_INSTALL_PREFIX=$PWD/dist" "-DCMAKE_TOOLCHAIN_FILE=$Env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"
          cmake --build build --target install --config Release
      - name: Build solution
        run: dotnet build --configuration Release
      - name: Clean output
        run: |
          rm src/PinJuke/bin/Release/PinJuke/Configs/Playlists/.gitignore
          rm src/PinJuke/bin/Release/PinJuke/Media/Videos/.gitignore
          rm src/PinJuke/bin/Release/PinJuke/Milkdrop/Presets/.gitignore
          rm src/PinJuke/bin/Release/PinJuke/Milkdrop/Textures/.gitignore
          rm src/PinJuke/bin/Release/PinJuke/ffmpeg/.gitignore
      - name: Create zip archive
        # https://github.com/marketplace/actions/zip-release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: zip
          # e.g. PinJuke_App_1.0.0-alpha.1.zip
          filename: PinJuke_App_${{ github.ref_name }}.zip
          directory: src/PinJuke/bin/Release
          path: PinJuke
      - name: Upload release
        # https://github.com/ncipollo/release-action
        uses: ncipollo/release-action@v1
        with:
          artifacts: src/PinJuke/bin/Release/PinJuke_App_${{ github.ref_name }}.zip
